### PR TITLE
Added first speakers

### PR DESCRIPTION
**Pull request by zasadnyy**

### CODE REVIEW

**Comment by zasadnyy** [comment]
Data that should get to the Firebase:

```
[ {
  "company" : "Archilogic",
  "companyLogo" : "/images/logos/archilogic.png",
  "country" : "Switzerland",
  "featured" : true,
  "id" : 1,
  "name" : "Martin Splitt",
  "photoUrl" : "/images/people/martin_splitt.jpg",
  "title" : "Lead Engineer"
}, {
  "company" : "Stanfy",
  "companyLogo" : "/images/logos/stanfy.svg",
  "country" : "Ukraine",
  "featured" : true,
  "id" : 2,
  "name" : "Michael Pustovit",
  "photoUrl" : "/images/people/michael_pustovit.jpg",
  "title" : "Senior Android Developer"
}, {
  "company" : "Runtastic",
  "companyLogo" : "/images/logos/runtastic.png",
  "country" : "Austria",
  "featured" : true,
  "id" : 3,
  "name" : "Lesya Danylyuk",
  "photoUrl" : "/images/people/lesya_danylyuk.jpg",
  "title" : "UX Designer"
} ]
```

**Comment by ozasadnyy** [comment]
@zasadnyy Please open PR against master branch

**Comment by webknjaz** [comment]
you may edit the target branch in this PR :)

**Comment by webknjaz** [comment]
(changed base)

**Comment by ozasadnyy** [comment]
@webknjaz wow, I didn't know that

**Pull request merged**
